modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/Spelled/issues"
license="MIT"

[[mods]]
modId="spelled"
version="${file.jarVersion}"
displayName="Spelled"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spelled"
authors="Mrbysco, Kara2810"
description='''
It's spelled "Yu Mo Gui Gwai Fai Di Zao"
'''

[[dependencies.spelled]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.spelled]]
modId="patchouli"
mandatory=true
versionRange="[1.18.1-61,)"
ordering="NONE"
side="BOTH"